
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'DB245B194B01920EA43DD8C40C2F431F'
    
_lr_action_items = {'DIVIDE':([4,8,10,14,15,21,23,25,26,27,28,29,30,31,32,],[-13,18,-14,18,-14,-11,18,18,-12,18,18,-10,18,-9,18,]),'BEGIN':([0,],[1,]),'END':([0,],[7,]),'NAME':([0,6,9,11,13,16,17,18,19,20,22,],[10,15,15,15,15,15,15,15,15,15,15,]),'DUMP':([0,],[3,]),'NUMBER':([0,6,9,11,13,16,17,18,19,20,22,],[4,4,4,4,4,4,4,4,4,4,4,]),'BEGIN_READONLY':([0,],[5,]),'TIMES':([4,8,10,14,15,21,23,25,26,27,28,29,30,31,32,],[-13,20,-14,20,-14,-11,20,20,-12,20,20,-10,20,-9,20,]),'EQUALS':([10,],[22,]),'PLUS':([4,8,10,14,15,21,23,25,26,27,28,29,30,31,32,],[-13,17,-14,17,-14,-11,17,17,-12,17,-7,-10,-8,-9,17,]),'LPAREN':([0,1,3,5,6,7,9,11,13,16,17,18,19,20,22,],[6,11,12,13,6,16,6,6,6,6,6,6,6,6,6,]),'RPAREN':([4,12,14,15,21,23,25,26,27,28,29,30,31,],[-13,24,26,-14,-11,33,34,-12,35,-7,-10,-8,-9,]),'MINUS':([0,4,6,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,],[9,-13,9,19,9,-14,9,9,19,-14,9,9,9,9,9,-11,9,19,19,-12,19,-7,-10,-8,-9,19,]),'$end':([2,4,8,10,15,21,24,26,28,29,30,31,32,33,34,35,],[0,-13,-6,-14,-14,-11,-4,-12,-7,-10,-8,-9,-5,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,9,11,13,16,17,18,19,20,22,],[8,14,21,23,25,27,28,29,30,31,32,]),'statement':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> BEGIN LPAREN expression RPAREN','statement',4,'p_statement_begin_transaction','adb.py',78),
  ('statement -> BEGIN_READONLY LPAREN expression RPAREN','statement',4,'p_statement_begin_readonly_transaction','adb.py',82),
  ('statement -> END LPAREN expression RPAREN','statement',4,'p_statement_end_transaction','adb.py',86),
  ('statement -> DUMP LPAREN RPAREN','statement',3,'p_statement_dump','adb.py',90),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','adb.py',94),
  ('statement -> expression','statement',1,'p_statement_expr','adb.py',98),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','adb.py',102),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','adb.py',103),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','adb.py',104),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','adb.py',105),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','adb.py',112),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','adb.py',116),
  ('expression -> NUMBER','expression',1,'p_expression_number','adb.py',120),
  ('expression -> NAME','expression',1,'p_expression_name','adb.py',124),
]
